[[ISSUERS]]
address = "rfXMq3BMX2dTzJtG4pnhr49u6sHkVQXpWL"
name = "XRMine"

[[TOKENS]]
issuer = "rfXMq3BMX2dTzJtG4pnhr49u6sHkVQXpWL"
currency = "58524D696E650000000000000000000000000000"
name = "XRMine"
desc = "XRMine is a platform to reward the xrpl community for their engagement"
icon = "https://handy4ndy.github.io/XRmine_0.0.1/assets/images/XRmineimage.png"

[[TOKENS.WEBLINKS]]
url = "https://handy4ndy.github.io/XRmine_0.0.1"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://handy4ndy.github.io/XRmine_0.0.1/whitepaper.html"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com/XRmine_info"
type = "socialmedia"